f = open('somefile.txt', 'w')
f.write('Hello, ')
f.write('World!')
f.close()

f = open('somefile.txt', 'r')
print(f.read(5))
print(f.read())
f.close()
print()

f = open('somefile.txt', 'r')
data = f.read()
print(type(data))
print(data)
print(f.read())
print(f.tell(), len(data))
f.seek(f.tell() - len(data))
print(f.read())
